global:
  scrape_interval: 5s  # Scrape every 5 seconds

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  # Alertmanager service

rule_files:
  - "alert_rules.yml"  # External alert rules file

scrape_configs:
  - job_name: 'fastapi-monitoring'
    static_configs:
      - targets: ['host.docker.internal:9999']  # test_2.py

  - job_name: 'comple_test'
    static_configs:
      - targets: ['host.docker.internal:6000']  # comple_test.py

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
